name: tagn
version: '${project.version}'
main: me.matt.tagn.Tagn
api-version: 1.19

commands:
  reset:
    description: resets the map
    usage: /<command>
    permission: tagn.canreset
  start:
    description: starts round
    usage: /<command>
    permission: tagn.startround
  wool:
    description: sets wool colour
    usage: /<command> <color> e.g. /wool light_blue
  addwool:
    description: adds wool colour
    usage: /<command> <player> <color>
    permission: tagn.addwool